import { type NextPage } from "next";
import Head from "next/head";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Field, Form, Formik, FormikHelpers } from 'formik'
import Base from "../layouts/Base";
import { useRouter } from "next/router";

interface Values {
  email: string;
  password: string;
}

const api = "http://localhost:4000/api"

const Signup: NextPage = () => {
  const router = useRouter();
  const signup = useMutation(["signup"], (values: Values) =>
    fetch(api + '/users/register', {
      method: 'POST',
      mode: 'cors',
      credentials: 'include',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(values)
    }
    ).then(res => res.json()), {
      onSuccess: (response) => {
        console.log(response)
        router.push("/login")
      },
    }
  )

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Base>
        <h1 className="font-bold text-2xl">Sign Up</h1>
        <Formik
          initialValues={{ email: '', password: '' }}
          onSubmit={(
            values: Values,
            { setSubmitting }: FormikHelpers<Values>
          ) => {
            setTimeout(() => {
              signup.mutate(values)
              setSubmitting(false)
            }, 500)
          }}
        >
          <Form className="flex items-center flex-col gap-4 p-5">
            <label className="font-bold text-xl" htmlFor="email">Email</label>
            <Field type="email" id="email" name="email" placeholder="john@doe.com" />
            <label className="font-bold text-xl" htmlFor="password">Password</label>
            <Field id="password" name="password" placeholder="******" />
            <button type="submit">Submit</button>
          </Form>
        </Formik>
      </Base>
    </>
  );
};

export default Signup;
